BUTTPLUG_SERVER_ADDRESS: ws://127.0.0.1:12345
BUTTPLUG_STRENGTH_MAX: '100'
CHARACTER_NAME: Neela
CHASTER_DEFEAT_MAX: '43200'
CHASTER_DEFEAT_MIN: '21600'
CHASTER_ENABLED: false
CHASTER_PUNISH_MAX: '28800'
CHASTER_PUNISH_MIN: '14400'
CHASTER_REFRESH_TOKEN: ''
CHASTER_TOKEN: ''
DD_VIB_MULT: '2'
ENABLED_INTERFACES:
- Log Reader
LOCK_NAME: Self-lock
LOG_PATH: C:/Users/ardisfoxx/AppData/Local/Google/Chrome/User Data/chrome_debug.log
LOVENSE_HOST: 192.168.1.187:20010
LOVENSE_STRENGTH_SCALE: '100'
LOVENSE_USE_NEW_API: true
MAUSTEC_HOST: ws://192.168.0.230:80
OUTPUT_IDX: '1'
PRINT_LOG_LINES: true
TOY_TYPE:
- Lovense
WARN_ON_STACK_DUMP: true
WARN_ON_STACK_DUMP_SOUND: false
WINDOW_UPDATE_FREQUENCY: '0.01'
XTOYS_SHOCK_MAX: '100'
XTOYS_SHOCK_MIN: '0'
XTOYS_WEBHOOK_ID: ''
